services:
  # NestJS 애플리케이션 서비스
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      # 데이터베이스 연결 정보
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: cla-corp

    restart: unless-stopped

  # MySQL 데이터베이스 서비스
  mysql:
    image: mysql:8.0
    container_name: cla-corp
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: cla-corp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:

